# Generated by Django 3.2 on 2022-09-06 07:13

import cloudinary.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('therapists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Therapy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('therapy_name', models.CharField(max_length=40, unique=True)),
                ('body_area', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(1, 'Head'), (2, 'Neck'), (3, 'Shoulders'), (4, 'Torso'), (5, 'Upper Legs'), (6, 'Lower Legs'), (7, 'Buttocks'), (8, 'Feet'), (9, 'Full Body'), (10, 'Upper Body'), (11, 'Lower Body'), (12, 'Back')]), size=None)),
                ('benefits', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('description', models.CharField(max_length=180)),
                ('duration', models.PositiveSmallIntegerField()),
                ('image', cloudinary.models.CloudinaryField(default='no_image', max_length=255, verbose_name='image')),
                ('duration_is_variable', models.BooleanField(default=False)),
                ('therapists', models.ManyToManyField(related_name='therapies', to='therapists.Therapist')),
            ],
            options={
                'ordering': ['-duration'],
            },
        ),
    ]
