# Generated by Django 3.2 on 2022-09-08 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapists', '0002_therapist_image_alt_text'),
        ('therapies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapy',
            name='image_alt_text',
            field=models.CharField(default='the therapy', max_length=80),
        ),
        migrations.AddField(
            model_name='therapy',
            name='specialism',
            field=models.ManyToManyField(related_name='specialism', to='therapists.Therapist'),
        ),
    ]
