# Generated by Django 3.2 on 2022-09-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapies', '0003_alter_therapy_specialism'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=15, unique=True)),
                ('order_position', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['order_position'],
            },
        ),
        migrations.RemoveField(
            model_name='therapy',
            name='body_area',
        ),
        migrations.AddField(
            model_name='therapy',
            name='body_area',
            field=models.ManyToManyField(related_name='body_area', to='therapies.BodyArea'),
        ),
    ]
