# Generated by Django 3.2 on 2022-09-16 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapies', '0004_auto_20220912_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapy',
            name='image_alt_text',
            field=models.CharField(blank=True, default='the therapy', max_length=80),
        ),
    ]
