# Generated by Django 3.2 on 2022-09-06 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('therapies', '0001_initial'),
        ('therapists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('date_time', models.DateField(auto_now_add=True)),
                ('user', models.CharField(max_length=30)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('content', models.CharField(max_length=220)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='therapists.therapist')),
                ('therapy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='therapies.therapy')),
            ],
        ),
    ]
