# Generated by Django 3.2 on 2022-09-08 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='image_alt_text',
            field=models.CharField(default='the therapist', max_length=80),
        ),
    ]
